'DeviceOwnerApp'
mas-satou/1eb pull request #3
Opened 2018-09-19 09:25 UTC by kasagawa-t

.gitignoreに記載されたファイルを除いたものになります。
よろしくお願い致します。

2018-09-20 08:07 UTC, mas-satou requested changes
不足ファイルのコミットとKioskモードの修正は別コミットにしてください

2018-09-28 06:31 UTC, kasagawa-t commented
Kioskモード修正をコミットしました。

2018-09-28 06:41 UTC, kasagawa-t commented
不足ファイルをコミットしました。

2018-10-03 00:59 UTC, mas-satou approved these changes

2018-10-03 00:59 UTC, mas-satou commented
問題ないので取り込みます

2018-10-03 00:59 UTC, closed without merging